name: Latest Twitter Tweets
on:
  schedule:
    # Runs once a day because using free tier Rss.app
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly.

jobs:
  update-readme-with-twitter:
    name: Update this repo's README with latest tweets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "TWITTER"
          feed_list: "https://rss.app/feeds/OdAP9ObMCraFsAQc.xml"
          commit_message: "Updated with the latest tweets"
          committer_username: "twitter-bot"
          committer_email: "twitter-bot@example.com"